### ISSUE TITLE
mapper文件的热部署是没问题，修改实体类上的注解不生效

### ISSUE THREAD

**Issue by Liang-Dongxing** [SweetInk/jrebel-mybatisplus#11]
![QQ截图20200728151828](https://user-images.githubusercontent.com/19583575/88632865-c8e92700-d0e6-11ea-8350-981b89f1b45a.png)

**Comment by Liang-Dongxing** [comment]
![QQ截图20200728151828](https://user-images.githubusercontent.com/19583575/88632975-f59d3e80-d0e6-11ea-9789-b1c586941e5e.png)

**Comment by SweetInk** [comment]
这个目前暂不支持哦
