### ISSUE TITLE
mybatisplus 3.4.0  加载问题

### ISSUE THREAD

**Issue by wangtaicheng** [SweetInk/jrebel-mybatisplus#12]
mybatisplus 3.4.0 中插件会导致MybatisConfiguration 调用父类的addMappedStatement 而子类的不执行

**Comment by SweetInk** [comment]
能具体描述下吗？以及产生的结果

**Comment by wangtaicheng** [comment]
![image](https://user-images.githubusercontent.com/6257526/91369335-1a97e500-e83e-11ea-87db-9921569f73b0.png)
![image](https://user-images.githubusercontent.com/6257526/91369408-4adf8380-e83e-11ea-9302-4f6549e2f242.png)
3.4.0 中用的是上面的的代码，这块有变动，插件中的这个可能需要改动。

**Comment by biexuxiaoyao** [comment]
3.4.0 的解决了么？ 目前明确的已支持的mybatis-plus最高版本是多少？

**Comment by SweetInk** [comment]
> 3.4.0 的解决了么？ 目前明确的已支持的mybatis-plus最高版本是多少？

本地测试`3.1.1`~`3.40`都支持，IDEA的插件都有时间更新下...

**Comment by fickleness-youth** [comment]
> > 3.4.0 的解决了么？ 目前明确的已支持的mybatis-plus最高版本是多少？
> 
> 本地测试`3.1.1`~`3.40`都支持，IDEA的插件等有时间更新下...

mybatisplus 3.5.X也会有这个问题
