### ISSUE TITLE
阅读你的plugin源码，麻烦这里解释一下

### ISSUE THREAD

**Issue by libinwalan** [SweetInk/jrebel-mybatisplus#19]
我看到plugin里 前面定义的
    private final static String MP_MARK_NAME = ".mybatisplus-jr-mark_";
    private final static String MP_3_4_0_ = ".mybatisplusV340-jr-mark_";

请问 mybatisplus-jr-mark_ 这是什么文件啊？干什么用的呢？

**Comment by SweetInk** [comment]
这个是用来检测是否项目中是否用了mybatis-plus

**Comment by libinwalan** [comment]
ok。thanks
