### ISSUE TITLE
请问现在在jetbrain插件市场安装了插件之后 , 还需要手动去打包插件源码 , 并修改VM配置吗?

### ISSUE THREAD

**Issue by aStudyMachine** [SweetInk/jrebel-mybatisplus#20]
我直接在插件市场装了插件之后 , 按照首页描述进行配置 , 修改mapper.xml文件重新编译 , 并没有打印任何日志... 不知道是不是使用方式有误

**Comment by aStudyMachine** [comment]
IDEA 版本是2021.2 , jrebel 插件版本是2021.3.1

**Comment by aStudyMachine** [comment]
看来是不用再配置了的, 安装了插件在Jrebel上重启应用就已经生效了, 只是没有作者所说的输出日志而已 . 😀

**Comment by SweetInk** [comment]
> 看来是不用再配置了的, 安装了插件在Jrebel上重启应用就已经生效了, 只是没有作者所说的输出日志而已 . 😀

没有日志就很奇怪，按理说不应该。

**Comment by aStudyMachine** [comment]
> > 看来是不用再配置了的, 安装了插件在Jrebel上重启应用就已经生效了, 只是没有作者所说的输出日志而已 . 😀
> 
> 没有日志就很奇怪，按理说不应该。

jrebel启动时有打印监测日志 , 但是更新mapper.xml时无打印sql reload log .. , 不影响使用 , 有时间可以瞅瞅啥原因
![Snipaste_2021-08-16_16-22-51](https://user-images.githubusercontent.com/27571297/129540711-eff8057b-c7e5-4508-9bd4-456a6e91d5e3.png)
