### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by bugman8688** [SweetInk/jrebel-mybatisplus#21]
您好，编译失败，请问工具现在还是生效的吗？

在IDEA下导入项目后，提示
Cannot resolve org.zeroturnaround:jr-javassist:3.20.0-GA-java4-zt

我检查了依赖的地址，https://repos.zeroturnaround.com/nexus/ 貌似已经无法正常访问了，可能是权限受限。

请问您可否提供一个release的包出来？

**Comment by SweetInk** [comment]
你说的release包是指这个插件还是，`jr-javassist:3.20.0-GA-java4-zt`

**Comment by SweetInk** [comment]
上面的仓库是可以正常访问的，如果你需要这个插件可以在IDEA的插件市场搜索下载
