### ISSUE TITLE
Fail to load descriptor from file 1.01.jar

### ISSUE THREAD

**Issue by giveup** [SweetInk/jrebel-mybatisplus#4]
idea无法本地安装，
版本是：
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019

**Comment by SweetInk** [comment]
@giveup 这个不是IDEA插件，如何使用，请参考[README.md](https://github.com/SweetInk/jrebel-mybatisplus/blob/master/README.md)

**Comment by giveup** [comment]
眼花...idea里装了jrebel，以为这个插件能直接用.
