### ISSUE TITLE
Eclipse下 java.lang.NullPointerException

### ISSUE THREAD

**Issue by michael0952** [SweetInk/jrebel-mybatisplus#9]
开发环境:Mac
Eclipse：4.14.0
mybatis-plus 版本:3.3.1
解压jar包:/Users/zx/Documents/server/JrebelHotReload 
添加该项目的VM参数：-Drebel.plugins=/Users/*/Documents/server/JrebelHotReload/jr-mybatisplus.jar

输出多了一句日志：JRebel: Ready config JRebel MybatisPlus plugin...
但是仍然无法自动更新，错误如下
![image](https://user-images.githubusercontent.com/20938747/75864276-bb33bc00-5e3c-11ea-806c-5312e0a212ac.png)

**Comment by SweetInk** [comment]
看下你的mybatis-plus配置文件，以及你使用的`jr-mybatisplus.jar`版本是多少？

**Comment by michael0952** [comment]
jr-mybatisplus.jar 就是3.3.1
```
    <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus</artifactId>
        <version>3.3.1</version>
    </dependency>
```
配置文件:	

	<bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
		
		<property name="dataSource" ref="dataSource"/>
		
		<property name="configLocation" value="classpath:/mybatis/mybatis-config.xml"/>
		
		<property name="mapperLocations" value="classpath:/mybatis/mappers/*.xml"/>
		
		<property name="typeAliasesPackage" value="com.jt.manage.pojo"/>
       
	</bean>

    <bean id="globalConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig">
    <property name="dbConfig" ref="dbConfig"/> 
    
    </bean>

    <bean id="dbConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig.DbConfig">
        <property name="tablePrefix" value="tb_"/>
    </bean>
	
	
	
	<bean id="mapperScanner" class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		
		<property name="basePackage" value="com.*.*.mapper"/>
	</bean>

**Comment by SweetInk** [comment]
`jr-mybatisplus.jar`我目前发布的最新版本才`1.0.2`
[所有Release](https://github.com/SweetInk/jrebel-mybatisplus/releases)

**Comment by michael0952** [comment]
应该说，是mybatis-plus 版本:3.3.1
之前下载的不是最新包
下载最新的包1.0.2后可以了，谢谢
